const hre = require("hardhat");
const { ethers } = hre;

async function main() {
  const signers = await ethers.getSigners();
  const [deployer, manufacturer, verifier] = signers;

  console.log("=========================================");
  console.log(" AntiCounterfeit Deployment");
  console.log("=========================================");
  console.log("Network:", hre.network.name);
  console.log("Deploying contracts with account:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH");

  const AntiCounterfeit = await ethers.getContractFactory("AntiCounterfeit");
  const antiCounterfeit = await AntiCounterfeit.deploy(deployer.address);
  await antiCounterfeit.waitForDeployment();

  const contractAddress = await antiCounterfeit.getAddress();
  console.log("\nAntiCounterfeit deployed to:", contractAddress);

  const MANUFACTURER_ROLE = await antiCounterfeit.MANUFACTURER_ROLE();
  const VERIFIER_ROLE = await antiCounterfeit.VERIFIER_ROLE();

  // Grant initial MANUFACTURER_ROLE / VERIFIER_ROLE if additional signers are available
  // (e.g. on a local Hardhat network with multiple default accounts).
  if (manufacturer) {
    const tx1 = await antiCounterfeit.connect(deployer).grantRole(MANUFACTURER_ROLE, manufacturer.address);
    await tx1.wait();
    console.log("Granted MANUFACTURER_ROLE to:", manufacturer.address);
  } else {
    console.log("No secondary signer available to grant MANUFACTURER_ROLE. Skipping.");
  }

  if (verifier) {
    const tx2 = await antiCounterfeit.connect(deployer).grantRole(VERIFIER_ROLE, verifier.address);
    await tx2.wait();
    console.log("Granted VERIFIER_ROLE to:", verifier.address);
  } else {
    console.log("No tertiary signer available to grant VERIFIER_ROLE. Skipping.");
  }

  console.log("\n=========================================");
  console.log(" Deployment Summary");
  console.log("=========================================");
  console.log("Contract Address :", contractAddress);
  console.log("Admin            :", deployer.address);
  console.log("Manufacturer     :", manufacturer ? manufacturer.address : "N/A");
  console.log("Verifier         :", verifier ? verifier.address : "N/A");

  console.log("\n-----------------------------------------");
  console.log(" ABI Export Instructions");
  console.log("-----------------------------------------");
  console.log("The full contract artifact (including ABI) is generated by `hardhat compile` at:");
  console.log("  artifacts/contracts/AntiCounterfeit.sol/AntiCounterfeit.json");
  console.log("\nTo export ONLY the ABI array for frontend/backend integration, run:");
  console.log('  node -e "console.log(JSON.stringify(require(\'./artifacts/contracts/AntiCounterfeit.sol/AntiCounterfeit.json\').abi, null, 2))" > AntiCounterfeit.abi.json');
  console.log("\nTo verify the contract on Etherscan (Sepolia), run:");
  console.log(`  npx hardhat verify --network sepolia ${contractAddress} ${deployer.address}`);
  console.log("=========================================\n");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
